### ISSUE TITLE
leading 0

### ISSUE THREAD

**Issue by Chathula** [lakshmajim/otp#2]
i generate length 6 OTP. when it saves on db it only has 5 chars. i think leading 0 has been missed when saving to db. need to check if OTP is with leading 0 and regenerate i think.

thank you

**Comment by lakshmaji** [comment]
Hi @Chathula ,
It might be issue with database column length (VARCHAR or the data type that suits your application / database)

**Comment by Chathula** [comment]
Thank You.. solved!
